import slugify from 'slugify';
const data = {
  products: [
    {
      // _id: '1',
      name: 'Free Shirt',
      slug: slugify('Free Shirt', { lower: true }),
      department: 'Fashion',
      category: 'Men Fashion',
      subcategory: 'Shirts',
      image: '/images/shirt1.jpg',
      images: [],
      cities: [],
      transactions: [],
      price: 70,
      brand: 'Nike',
      reviews: [],
      rating: 4.5,
      numReviews: 10,
      countInStock: 50,
      description: 'A popular shirt demanded by 80% customers',
      isBestSeller: true,
      isDiscounted: false,
      isToprated: true,
      sold: 10,
      views: 15,
      buyPrice: 50,
      oldPrice: 70,
      discount: 0,
      featured: 1,
    },
    {
      // _id: '2',
      name: 'Fit Shirt',
      slug: slugify('Fit Shirt', { lower: true }),
      department: 'Fashion',
      category: 'Men Fashion',
      subcategory: 'Shirts',
      image: '/images/shirt2.jpg',
      images: [],
      cities: [],
      transactions: [],
      price: 80,
      brand: 'Sally',
      reviews: [],
      rating: 3.5,
      numReviews: 5,
      countInStock: 50,
      description: 'Smart looking Shirt',
      isBestSeller: true,
      isDiscounted: true,
      isToprated: true,
      sold: 5,
      views: 50,
      buyPrice: 70,
      oldPrice: 80,
      discount: 0,
      featured: 2,
    },
    {
      // _id: '3',
      name: 'Slim Shirt',
      slug: slugify('Slim Shirt', { lower: true }),
      department: 'Fashion',
      category: 'Men Fashion',
      subcategory: 'Shirts',
      image: '/images/shirt3.jpg',
      images: [],
      cities: [],
      transactions: [],
      price: 70,
      brand: 'Raymond',
      reviews: [],
      rating: 5,
      numReviews: 8,
      countInStock: 50,
      description: 'Slim fitted pants',
      isBestSeller: false,
      isDiscounted: false,
      isToprated: true,
      sold: 25,
      views: 10,
      buyPrice: 50,
      oldPrice: 87,
      discount: 0,
      featured: 1,
    },
    {
      // _id: '4',
      name: 'Golf Pants',
      slug: slugify('Golf Pants', { lower: true }),
      department: 'Fashion',
      category: 'Men Fashion',
      subcategory: 'Pants',
      image: '/images/pants1.jpg',
      images: ['/images/pants11.jpg'],
      cities: [],
      transactions: [],
      price: 90,
      brand: 'Oliver',
      reviews: [],
      rating: 3,
      numReviews: 6,
      countInStock: 20,
      description: 'Smart looking pants',
      isBestSeller: true,
      isDiscounted: false,
      isToprated: true,
      sold: 2,
      views: 100,
      buyPrice: 80,
      oldPrice: 100,
      discount: 0,
      featured: 1,
    },
    {
      // _id: '5',
      name: 'Fit Pants',
      slug: slugify('Fit Pants', { lower: true }),
      department: 'Fashion',
      category: 'Men Fashion',
      subcategory: 'Pants',
      image: '/images/pants2.jpg',
      images: [],
      cities: [],
      transactions: [],
      price: 84,
      brand: 'Zara',
      reviews: [],
      rating: 4.5,
      numReviews: 5,
      countInStock: 20,
      description: 'Smart looking pants',
      isBestSeller: true,
      isDiscounted: true,
      isToprated: true,
      sold: 1,
      views: 100,
      buyPrice: 70,
      oldPrice: 84,
      discount: 0,
      featured: 1,
    },
    {
      // _id: '6',
      name: 'Classic Pants',
      slug: slugify('Classic Pants', { lower: true }),
      department: 'Fashion',
      category: 'Men Fashion',
      subcategory: 'Pants',
      image: '/images/pants3.jpg',
      images: [],
      cities: [],
      transactions: [],
      price: 72,
      brand: 'Casely',
      reviews: [],
      rating: 4,
      numReviews: 7,
      countInStock: 100,
      description: 'Smart looking Shirt',
      isBestSeller: true,
      isDiscounted: false,
      isToprated: true,
      sold: 70,
      views: 80,
      buyPrice: 60,
      oldPrice: 80,
      discount: 0,
      featured: 1,
    },
  ],
};

export default data;
